[#advanced-config-engine]
= MultiClusterEngine advanced configuration 

{product-title} is installed using an operator that deploys all of the required components. {product-title-short} can be further configured during or after installation by adding one or more of the following attributes to the MultiClusterEngine custom resource:

[#custom-image-pull-secret]
== Custom Image Pull Secret

. If you plan to import Kubernetes clusters that were not created by {ocp-short} or {product-title-short}, generate a secret that contains your {ocp-short} pull secret information to access the entitled content from the distribution registry. 

+
The secret requirements for {ocp-short} clusters are automatically resolved by {ocp-short} and {product-title-short}, so you do not have to create the secret if you are not importing other types of Kubernetes clusters to be managed.

+
*Important:* These secrets are namespace-specific, so make sure that you are in the namespace that you use for your engine.

 .. Download your {ocp-short} pull secret file from https://cloud.redhat.com/openshift/install/pull-secret[cloud.redhat.com/openshift/install/pull-secret] by selecting *Download pull secret*.
Your {ocp-short} pull secret is associated with your Red Hat Customer Portal ID, and is the same across all Kubernetes providers.
 .. Run the following command to create your secret:
+
----
oc create secret generic <secret> -n <namespace> --from-file=.dockerconfigjson=<path-to-pull-secret> --type=kubernetes.io/dockerconfigjson
----
+
Replace `secret` with the name of the secret that you want to create.
Replace `namespace` with your project namespace, as the secrets are namespace-specific.
Replace `path-to-pull-secret` with the path to your {ocp-short} pull secret that you downloaded.

The following examples shows the template to use if you want to use a custom pull secret. Replace `namespace` with the name of your project namespace. Replace `secret` with the name of your pull secret:

[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec:
  imagePullSecret: <secret>
----


[#(target-namespace)]
== Target namespace

. The operands of the {product-title-short} can be installed in a designated namespace, by specifying a location in the {product-title-short}. This namespace will be created upon application of {product-title-short}.

*Important* If no target namespace is specified, the namespace of the operator will be used for the operands and will be stated in the {product-title-short} spec.

The following example shows the template if you want to specify a taarget namespace. Replace `target` with the name of your destination namespace

[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec:
  targetNamespace: <target>
----

