[#importing-a-managed-cluster-with-the-cli]
= Importing a managed cluster with the CLI

After you install {product-title}, you are ready to import a cluster to manage.
You can import from both the console and the CLI.
Follow this procedure to import from the CLI.

* <<cli-prerequisites,Prerequisites>>
* <<supported-architecture,Supported architecture>>
* <<importing-the-klusterlet,Importing the klusterlet>>

[#cli-prerequisites]
== Prerequisites

* You need a {product-title} engine cluster that is deployed.
If you are importing bare metal clusters, you must have the engine cluster installed on {ocp} version 4.6 or later. 
* You need a separate cluster that you want to manage and Internet connectivity.
* You need the {ocp} CLI version 4.6 or later, to run `oc` commands. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.8/html/cli_tools/openshift-cli-oc#cli-getting-started[Getting started with the OpenShift CLI] for information about installing and configuring the Red Hat OpenShift CLI, `oc`.
* You need to install the Kubernetes CLI, `kubectl`.
To install `kubectl`, see _Install and Set Up kubectl_ in the https://kubernetes.io/docs/tasks/tools/install-kubectl/[Kubernetes documentation].
+
*Note:* Download the installation file for CLI tools from the console.
* If you are importing a cluster that was not created by {ocp}, you need a `multiclusterengine.spec.imagePullSecret` defined. This secret might have been created when {product-title} was installed. See link:../adv_config_install.adoc#custom-image-pull-secret[Custom Image Pull Secret] for more information about defining the secret. 

[#supported-architecture]
== Supported architectures

* Linux (x86_64, s390x, ppc64le)
* macOS

[#prepare-for-import]
== Prepare for import

. Log in to your _engine cluster_.
Run the following command:
+
----
oc login
----

. Run the following command on the engine cluster to create the namespace.
*Note:* The cluster name that is defined in `<cluster_name>` is also used as the cluster namespace in the `.yaml` file file and commands:
+
----
oc new-project ${CLUSTER_NAME}
oc label namespace ${CLUSTER_NAME} cluster.open-cluster-management.io/managedCluster=${CLUSTER_NAME}
----

. Edit the example ManagedCluster with the following sample of YAML:
+
----
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: <cluster_name>
spec:
  hubAcceptsClient: true
----

. Save the file as `managed-cluster.yaml`.
. Apply the YAML file with the following command:
+
----
oc apply -f managed-cluster.yaml
----

The ManagedCluster-Import-Controller will generate a secret named `+${CLUSTER_NAME}-import+`. The `+${CLUSTER_NAME}-import+` secret contains the `import.yaml` that the user applies to a managed cluster to install klusterlet.

[#importing-the-klusterlet]

== Importing the klusterlet

*Important:* The import command contains pull secret information that is copied to each of the imported clusters.
Anyone who can access the imported clusters can also view the pull secret information.

. Obtain the `klusterlet-crd.yaml` that was generated by the managed cluster import controller.
+
Run the following command:
+
[source,bash]
----
oc get secret ${CLUSTER_NAME}-import -n ${CLUSTER_NAME} -o jsonpath={.data.crds\\.yaml} | base64 --decode > klusterlet-crd.yaml
----

. Obtain the `import.yaml` that was generated by the managed cluster import controller.
Run the following command:
+
[source,bash]
----
oc get secret ${CLUSTER_NAME}-import -n ${CLUSTER_NAME} -o jsonpath={.data.import\\.yaml} | base64 --decode > import.yaml
----

. Log in to your target _managed_ cluster.
. Apply the `klusterlet-crd.yaml` that was generated in step 1.
Run the following command:
+
----
kubectl apply -f klusterlet-crd.yaml
----

. Apply the `import.yaml` file that was generated in step 2.
Run the following command:
+
----
kubectl apply -f import.yaml
----

. Validate the pod status on the target managed cluster.
Run the following command:
+
----
kubectl get pod -n open-cluster-management-agent
----

. Validate `JOINED` and `AVAILABLE` status for your imported cluster.
Run the following command from the _engine_ cluster:
+
----
kubectl get managedcluster ${CLUSTER_NAME}
----

. Addons will be installed after the managed cluster is `AVAILABLE`. Validate the pod status of addons on the target managed cluster.
Run the following command:
+
----
kubectl get pod -n open-cluster-management-agent-addon
----
