[#importing-a-cluster]
= Importing a cluster

After you install multicluster engine for Kubernetes, you are ready to import a cluster to manage with the multicluster engine for Kubernetes.
Using the OpenShift Container Platform CLI, you can import a cluster using the `kubeconfig` file of the cluster to be imported. Alternatively, you can run import commands manually on the cluster to be imported.
Follow this procedure to import from the CLI.

* <<cli-prerequisites,Prerequisites>>
* <<supported-architecture,Supported architecture>>
* <<importing-wth-the-kubeconfig-file,Importing with the kubeconfig file>>
* <<importing-with-manual-commands,Importing with manual commands>>
* <<detaching-managed-cluster,Detaching a managed cluster>>

[#cli-prerequisites]
== Prerequisites

* You need a multicluster engine for Kubernetes cluster that is deployed.
If you are importing bare metal clusters, you must have the engine cluster installed on OpenShift Container Platform version 4.6 or later. 
* You need a separate cluster that you want to manage and Internet connectivity.
* You need the OpenShift Container Platform CLI version 4.6 or later, to run `oc` commands. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.8/html/cli_tools/openshift-cli-oc#cli-getting-started[Getting started with the OpenShift CLI] for information about installing and configuring the Red Hat OpenShift CLI, `oc`.

+
*Note:* Download the installation file for CLI tools from the console.
* If you are importing a cluster that was not created by OpenShift Container Platform, you need a `multiclusterengine.spec.imagePullSecret` defined. This secret might have been created when multicluster engine for Kubernetes was installed. See link:../adv_config_install.adoc#custom-image-pull-secret[Custom Image Pull Secret] for more information about defining the secret. 

[#supported-architecture]
== Supported architectures

* Linux (x86_64, s390x, ppc64le)
* macOS

[#prepare-for-import]
== Prepare for import

. Log in to your _multicluster engine for Kubernetes cluster_.
Run the following command:
+
----
oc login
----

. Run the following command on the engine cluster to create the namespace.
*Note:* The cluster name that is defined in `CLUSTER_NAME` is also used as the cluster namespace in the `.yaml` file and commands:
+
----
oc new-project ${CLUSTER_NAME}
oc label namespace ${CLUSTER_NAME} cluster.open-cluster-management.io/managedCluster=${CLUSTER_NAME}
----

. Edit the example ManagedCluster with the following sample of YAML:
+
----
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  hubAcceptsClient: true
----

. Save the file as `managed-cluster.yaml`.
. Apply the YAML file with the following command:
+
----
oc apply -f managed-cluster.yaml
----

[#importing-wth-the-kubeconfig-file]
== Importing with the kubeconfig file

. Retrieve the `kubeconfig` file of the cluster to be imported.

. Log in to your _multicluster engine for Kubernetes cluster_. 
Run the following command:
+
----
oc login
----

. Generate the import secret in the `${CLUSTER_NAME}` namespace using the `kubeconfig` file of the cluster to be imported.
Run the following command:
+
----
oc create secret generic auto-import-secret --from-file=kubeconfig=./path/to/kubeconfig-file -n ${CLUSTER_NAME}
----

+
*Note:* The import secret is used once and deleted when the import process completes.

. Validate the `JOINED` and `AVAILABLE` status for your imported cluster. Run the following command from the multicluster engine for Kubernetes cluster:
+
----
oc get managedcluster ${CLUSTER_NAME}
----

. Log in to your _cluster to be imported_. 
Run the following command:
+
----
oc login
----

. Validate the pod status on the cluster to be imported. 
Run the following command:
+
----
oc get pod -n open-cluster-management-agent
----

. Addons will be installed after the cluster to be imported is `AVAILABLE`. Validate the pod status of addons on the cluster to be imported. 
Run the following command:
+
----
kubectl get pod -n open-cluster-management-agent-addon
----

Your cluster is now imported.

[#importing-with-manual-commands]
== Importing with manual command

*Important:* The import command contains pull secret information that is copied to each of the imported clusters.
Anyone who can access the imported clusters can also view the pull secret information.

. Obtain the `klusterlet-crd.yaml` that was generated by the import controller on the cluster to be imported.
+
Run the following command:
+
[source,bash]
----
oc get secret ${CLUSTER_NAME}-import -n ${CLUSTER_NAME} -o jsonpath={.data.crds\\.yaml} | base64 --decode > klusterlet-crd.yaml
----

. Obtain the `import.yaml` that was generated by the import controller on the cluster to be imported.
Run the following command:
+
[source,bash]
----
oc get secret ${CLUSTER_NAME}-import -n ${CLUSTER_NAME} -o jsonpath={.data.import\\.yaml} | base64 --decode > import.yaml
----

. Log in to your target _managed_ cluster.
. Apply the `klusterlet-crd.yaml` that was generated in step 1.
Run the following command:
+
----
oc apply -f klusterlet-crd.yaml
----

. Apply the `import.yaml` file that was generated in step 2.
Run the following command:
+
----
oc apply -f import.yaml
----

. Validate the pod status on the cluster to be imported.
Run the following command:
+
----
oc get pod -n open-cluster-management-agent
----

. Validate `JOINED` and `AVAILABLE` status for your imported cluster.
Run the following command from the _engine_ cluster:
+
----
oc get managedcluster ${CLUSTER_NAME}
----

. Addons will be installed after the cluster to be imported is `AVAILABLE`. Validate the pod status of addons on the cluster to be imported.
Run the following command:
+
----
oc get pod -n open-cluster-management-agent-addon
----

Your cluster is now imported.

[#detaching-managed-cluster]
== Detaching a managed cluster

To detach a managed cluster from the multicluster engine for Kubernetes cluster, run the following command:

----
oc delete managedcluster ${CLUSTER_NAME}
----
