[#discovered-clusters-api]
= API

[[_mce_jsonoverview]]
== Overview
This documentation is for the MultiClusterEngine resource for multicluster engine for Kubernetes. The `MultiClusterEngine` resource has four possible requests: create, query, delete, and update.


=== Version information
[%hardbreaks]
__Version__ : 2.3.0


=== Contact information
[%hardbreaks]
__Contact Email__ : apiteam@swagger.io


=== License information
[%hardbreaks]
__License__ : Apache 2.0
__License URL__ : http://www.apache.org/licenses/LICENSE-2.0.html
__Terms of service__ : http://swagger.io/terms/


=== URI scheme
[%hardbreaks]
__BasePath__ : /kubernetes/apis
__Schemes__ : HTTPS


=== Tags

* MultiClusterEngines.discovery.open-cluster-management.io : Create and manage MultiClusterEngines


=== External Docs
[%hardbreaks]
__Description__ : Find out more about Swagger.
__URL__ : http://swagger.io


[[_mce-docs_apis_MultiClusterEngine_jsonpaths]]
== Paths

[[_mce-docs_apis_MultiClusterEngine_jsoncreateMultiClusterEngine]]
=== Create a MultiClusterEngine
....
POST /app.k8s.io/v1alpha1/namespaces/{namespace}/MultiClusterEngines
....


==== Description
Create a MultiClusterEngine.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|**Body**|**body** +
__required__|Parameters describing the MultiClusterEngine to be created.|MultiClusterEngine
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `MultiClusterEngines/yaml`


==== Tags

* MultiClusterEngines.discovery.open-cluster-management.io

===== Request body

[source,json]
----
{
  "apiVersion": "apiextensions.k8s.io/v1",
  "kind": "CustomResourceDefinition",
  "metadata": {
    "annotations": {
      "controller-gen.kubebuilder.io/version": "v0.4.1"
    },
    "creationTimestamp": null,
    "name": "multiclusterengines.multicluster.openshift.io"
  },
  "spec": {
    "group": "multicluster.openshift.io",
    "names": {
      "kind": "MultiClusterEngine",
      "listKind": "MultiClusterEngineList",
      "plural": "multiclusterengines",
      "shortNames": [
        "mce"
      ],
      "singular": "multiclusterengine"
    },
    "scope": "Cluster",
    "versions": [
      {
        "additionalPrinterColumns": [
          {
            "description": "The overall state of the MultiClusterEngine",
            "jsonPath": ".status.phase",
            "name": "Status",
            "type": "string"
          },
          {
            "jsonPath": ".metadata.creationTimestamp",
            "name": "Age",
            "type": "date"
          }
        ],
        "name": "v1alpha1",
        "schema": {
          "openAPIV3Schema": {
            "description": "MultiClusterEngine is the Schema for the multiclusterengines\nAPI",
            "properties": {
              "apiVersion": {
                "description": "APIVersion defines the versioned schema of this representation\nof an object. Servers should convert recognized schemas to the latest\ninternal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
                "type": "string"
              },
              "kind": {
                "description": "Kind is a string value representing the REST resource this\nobject represents. Servers may infer this from the endpoint the client\nsubmits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
                "type": "string"
              },
              "metadata": {
                "type": "object"
              },
              "spec": {
                "description": "MultiClusterEngineSpec defines the desired state of MultiClusterEngine",
                "properties": {
                  "imagePullSecret": {
                    "description": "Override pull secret for accessing MultiClusterEngine\noperand and endpoint images",
                    "type": "string"
                  },
                  "nodeSelector": {
                    "additionalProperties": {
                      "type": "string"
                    },
                    "description": "Set the nodeselectors",
                    "type": "object"
                  },
                  "targetNamespace": {
                    "description": "Location where MCE resources will be placed",
                    "type": "string"
                  },
                  "tolerations": {
                    "description": "Tolerations causes all components to tolerate any taints.",
                    "items": {
                      "description": "The pod this Toleration is attached to tolerates any\ntaint that matches the triple <key,value,effect> using the matching\noperator <operator>.",
                      "properties": {
                        "effect": {
                          "description": "Effect indicates the taint effect to match. Empty\nmeans match all taint effects. When specified, allowed values\nare NoSchedule, PreferNoSchedule and NoExecute.",
                          "type": "string"
                        },
                        "key": {
                          "description": "Key is the taint key that the toleration applies\nto. Empty means match all taint keys. If the key is empty,\noperator must be Exists; this combination means to match all\nvalues and all keys.",
                          "type": "string"
                        },
                        "operator": {
                          "description": "Operator represents a key's relationship to the\nvalue. Valid operators are Exists and Equal. Defaults to Equal.\nExists is equivalent to wildcard for value, so that a pod\ncan tolerate all taints of a particular category.",
                          "type": "string"
                        },
                        "tolerationSeconds": {
                          "description": "TolerationSeconds represents the period of time\nthe toleration (which must be of effect NoExecute, otherwise\nthis field is ignored) tolerates the taint. By default, it\nis not set, which means tolerate the taint forever (do not\nevict). Zero and negative values will be treated as 0 (evict\nimmediately) by the system.",
                          "format": "int64",
                          "type": "integer"
                        },
                        "value": {
                          "description": "Value is the taint value the toleration matches\nto. If the operator is Exists, the value should be empty,\notherwise just a regular string.",
                          "type": "string"
                        }
                      },
                      "type": "object"
                    },
                    "type": "array"
                  }
                },
                "type": "object"
              },
              "status": {
                "description": "MultiClusterEngineStatus defines the observed state of MultiClusterEngine",
                "properties": {
                  "components": {
                    "items": {
                      "description": "ComponentCondition contains condition information for\ntracked components",
                      "properties": {
                        "kind": {
                          "description": "The resource kind this condition represents",
                          "type": "string"
                        },
                        "lastTransitionTime": {
                          "description": "LastTransitionTime is the last time the condition\nchanged from one status to another.",
                          "format": "date-time",
                          "type": "string"
                        },
                        "message": {
                          "description": "Message is a human-readable message indicating\ndetails about the last status change.",
                          "type": "string"
                        },
                        "name": {
                          "description": "The component name",
                          "type": "string"
                        },
                        "reason": {
                          "description": "Reason is a (brief) reason for the condition's\nlast status change.",
                          "type": "string"
                        },
                        "status": {
                          "description": "Status is the status of the condition. One of True,\nFalse, Unknown.",
                          "type": "string"
                        },
                        "type": {
                          "description": "Type is the type of the cluster condition.",
                          "type": "string"
                        }
                      },
                      "type": "object"
                    },
                    "type": "array"
                  },
                  "conditions": {
                    "items": {
                      "properties": {
                        "lastTransitionTime": {
                          "description": "LastTransitionTime is the last time the condition\nchanged from one status to another.",
                          "format": "date-time",
                          "type": "string"
                        },
                        "lastUpdateTime": {
                          "description": "The last time this condition was updated.",
                          "format": "date-time",
                          "type": "string"
                        },
                        "message": {
                          "description": "Message is a human-readable message indicating\ndetails about the last status change.",
                          "type": "string"
                        },
                        "reason": {
                          "description": "Reason is a (brief) reason for the condition's\nlast status change.",
                          "type": "string"
                        },
                        "status": {
                          "description": "Status is the status of the condition. One of True,\nFalse, Unknown.",
                          "type": "string"
                        },
                        "type": {
                          "description": "Type is the type of the cluster condition.",
                          "type": "string"
                        }
                      },
                      "type": "object"
                    },
                    "type": "array"
                  },
                  "phase": {
                    "description": "Latest observed overall state",
                    "type": "string"
                  }
                },
                "type": "object"
              }
            },
            "type": "object"
          }
        },
        "served": true,
        "storage": true,
        "subresources": {
          "status": {}
        }
      }
    ]
  },
  "status": {
    "acceptedNames": {
      "kind": "",
      "plural": ""
    },
    "conditions": [],
    "storedVersions": []
  }
}
----

[[_mce-docs_apis_MultiClusterEngine_jsonqueryoperator]]
=== Query all MultiClusterEngines
....
GET /operator.open-cluster-management.io/v1alpha1/namespaces/{namespace}/operator
....


==== Description
Query your discovered clusters operator for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `operator/yaml`


==== Tags

* MultiClusterEngines.discovery.open-cluster-management.io

[[_mce-docs_apis_MultiClusterEngine_jsondeleteoperator]]
=== Delete a MultiClusterEngine operator
....
DELETE /operator.open-cluster-management.io/v1alpha1/namespaces/{namespace}/operator/{MultiClusterEngines_name}
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**application_name** +
__required__|Name of the Discovered Cluster operator that you want to delete.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Tags

* MultiClusterEngines.operator.open-cluster-management.io


[[_mce-docs_apis_MultiClusterEngine_jsondefinitions]]
== Definitions

[[_mce-docs_apis_MultiClusterEngine_json_parameters]]
=== MultiClusterEngine

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|**apiVersion** +
__required__| The versioned schema of the MultiClusterEngines. |string
|**kind** +
__required__|String value that represents the REST resource. |string
|**metadata** +
__required__|Describes rules that define the resource.|object
|**spec** +
__required__|MultiClusterEngineSpec defines the desired state of MultiClusterEngine. | See _List of specs_ 
|===

[[_mce-docs_apis_MultiClusterEngine_specs]]
=== List of specs

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|**activityTimestamp** +
__optional__|MultiClusterEngines last available activity timestamp. |metav1.time
|**apiUrl** +
__required__|MultiClusterEngines API URL endpoint. |string
|**cloudProvider** +
__optional__|Cloud provider of MultiClusterEngine. |string
|**console** +
__optional__|MultiClusterEngines console URL endpoint. |string
|**creationTimestamp** +
__optional__|MultiClusterEngines creation timestamp. |metav1.time
|**credential** +
__optional__| The reference to the credential from which the cluster was discovered. |corev1.ObjectReference
|**displayName** +
__required__| The display name of the discovered cluster. |string
|**isManagedCluster** +
__required__| If true, cluster is managed by ACM. |boolean
|**name** +
__required__| The name of the MultiClusterEngine. |string
|**openshiftVersion** +
__optional__| The OpenShift version of the discovered cluster. |string
|**status** +
__optional__| The status of the discovered cluster. |string
|**type** +
__required__| The OpenShift flavor (ex. OCP, ROSA, etc.). |string
|===
