[#discovered-clusters-api]
= API

[[_mce_jsonoverview]]
== Overview
This documentation is for the MulticlusterEngine resource for {product-title}. The MulticlusterEngine resource has four possible requests: create, query, delete, and update.


=== Version information
[%hardbreaks]
__Version__ : 2.3.0


=== Contact information
[%hardbreaks]
__Contact Email__ : apiteam@swagger.io


=== License information
[%hardbreaks]
__License__ : Apache 2.0
__License URL__ : http://www.apache.org/licenses/LICENSE-2.0.html
__Terms of service__ : http://swagger.io/terms/


=== URI scheme
[%hardbreaks]
__BasePath__ : /kubernetes/apis
__Schemes__ : HTTPS


=== Tags

* MulticlusterEngines.discovery.open-cluster-management.io : Create and manage MulticlusterEngines


=== External Docs
[%hardbreaks]
__Description__ : Find out more about Swagger.
__URL__ : http://swagger.io


[[_mce-docs_apis_MulticlusterEngine_jsonpaths]]
== Paths

[[_mce-docs_apis_MulticlusterEngine_jsoncreateMulticlusterEngine]]
=== Create a MulticlusterEngine
....
POST /app.k8s.io/v1alpha1/namespaces/{namespace}/MulticlusterEngines
....


==== Description
Create a MulticlusterEngine.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|**Body**|**body** +
__required__|Parameters describing the MulticlusterEngine to be created.|MulticlusterEngine
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `MulticlusterEngines/yaml`


==== Tags

* MulticlusterEngines.discovery.open-cluster-management.io

===== Request body

[source,json]
----
JSON HERE--Use YAML to JSON tool
----

[[_mce-docs_apis_MulticlusterEngine_jsonqueryoperator]]
=== Query all MulticlusterEngines
....
GET /operator.open-cluster-management.io/v1alpha1/namespaces/{namespace}/operator
....


==== Description
Query your discovered clusters operator for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `operator/yaml`


==== Tags

* MulticlusterEngines.discovery.open-cluster-management.io

[[_mce-docs_apis_MulticlusterEngine_jsondeleteoperator]]
=== Delete a MulticlusterEngine operator
....
DELETE /operator.open-cluster-management.io/v1alpha1/namespaces/{namespace}/operator/{MulticlusterEngines_name}
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**application_name** +
__required__|Name of the Discovered Cluster operator that you want to delete.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Tags

* MulticlusterEngines.operator.open-cluster-management.io


[[_mce-docs_apis_MulticlusterEngine_jsondefinitions]]
== Definitions

[[_mce-docs_apis_MulticlusterEngine_json_parameters]]
=== MulticlusterEngine

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|**apiVersion** +
__required__| The versioned schema of the MulticlusterEngines. |string
|**kind** +
__required__|String value that represents the REST resource. |string
|**metadata** +
__required__|Describes rules that define the resource.|object
|**spec** +
__required__|MulticlusterEngineSpec defines the desired state of MulticlusterEngine. | See _List of specs_ 
|===

[[_mce-docs_apis_MulticlusterEngine_specs]]
=== List of specs

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|**activityTimestamp** +
__optional__|MulticlusterEngines last available activity timestamp. |metav1.time
|**apiUrl** +
__required__|MulticlusterEngines API URL endpoint. |string
|**cloudProvider** +
__optional__|Cloud provider of MulticlusterEngine. |string
|**console** +
__optional__|MulticlusterEngines console URL endpoint. |string
|**creationTimestamp** +
__optional__|MulticlusterEngines creation timestamp. |metav1.time
|**credential** +
__optional__| The reference to the credential from which the cluster was discovered. |corev1.ObjectReference
|**displayName** +
__required__| The display name of the discovered cluster. |string
|**isManagedCluster** +
__required__| If true, cluster is managed by ACM. |boolean
|**name** +
__required__| The name of the MulticlusterEngine. |string
|**openshiftVersion** +
__optional__| The OpenShift version of the discovered cluster. |string
|**status** +
__optional__| The status of the discovered cluster. |string
|**type** +
__required__| The OpenShift flavor (ex. OCP, ROSA, etc.). |string
|===
