[#getting-started]
= Getting started

* <<introduction,Introduction>>
* <<create-and-manage-clusters,Create clusters>>
* <<todo, TODO>>

[#introduction]
== Introduction

Coming: Architecture and intro.

Before you install multicluster engine for Kubernetes, review the system configuration requirements and settings at link:../requirements.adoc#requirements-and-recommendations[Requirements and recommendations]. With a supported version of OpenShift Container Platform installed and running on your multicluster engine for Kubernetes cluster, you can proceed with link:../install_connected.adoc#installing-while-connected-online[Installing while connected online].

[#create-and-manage-clusters]
== Create and manage clusters

You are now ready to create and import clusters.
From your multicluster engine for Kubernetes cluster, you can create clusters from other Kubernetes services to manage.

. See link:../cluster
_create_cli.adoc#create-a-cluster[Create a cluster] to learn about the types of managed clusters you can create.
When you create a managed cluster, the new managed cluster imports automatically.
. If you have a cluster that you want to import manually, you can view link:../import_cli.adoc#importing-a-target-managed-cluster-to-the-hub-cluster[Importing a managed cluster with the CLI] to learn how to import a managed cluster.
. You can view link:../import_cli.adoc#detaching-managed-cluster[Detaching a managed cluster] when you no longer need to manage a cluster.

[#todo]
== TODO