[#uninstalling]
= Uninstalling

When you uninstall {product-title}, you see two different levels of the process: A _custom resource removal_ and a _complete operator uninstall_. It might take up to 5 minutes to complete the uninstall process.

- The custom resource removal is the most basic type of uninstall that removes the custom resource of the `MultiClusterEngine` instance but leaves other required operator resources. This level of uninstall is helpful if you plan to reinstall using the same settings and components.

- The second level is a more complete uninstall that removes most operator components, excluding components such as custom resource definitions. When you continue with this step, it removes all of the components and subscriptions that were not removed with the custom resource removal. After this uninstall, you must reinstall the operator before reinstalling the custom resource.

[#prerequisite-detach]
== Prerequisite: Detach enabled services

Before you uninstall the {product-title-short} engine, you must detach all of the clusters that are managed by that engine. To avoid errors, detach all clusters that are still managed by the engine, then try to uninstall again.

* If you have managed clusters attached, you might see the following message.
* 

+
----
Cannot delete MultiClusterEngine resource because ManagedCluster resource(s) exist
----

+
For more information about detaching clusters, see the _Removing a cluster from management_ section by selecting the information for your provider in link:../clusters/create.adoc#creating-a-cluster[Creating a cluster]. 

* If you have Bare metal assets, you might see the following:

+ 
----
Cannot delete MultiClusterEngine resource because BareMetalAssets resource(s) exist
----
+
For more information about removing the bare metal assets, see link:../clusters/bare_assets.adoc#removing-a-bare-metal-asset[Removing a bare metal asset].

[#removing-a-multiclusterengine-instance-by-using-commands]
== Removing resources by using commands

. If you have not already. ensure that your {ocp-short} CLI is configured to run `oc` commands. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.8/html/cli_tools/openshift-cli-oc#cli-getting-started[Getting started with the OpenShift CLI] in the {ocp-short} documentation for more information about how to configure the `oc` commands. 

. Change to your project namespace by entering the following command. Replace _namespace_ with the name of your project namespace:
+
----
oc project <namespace>
----

. Enter the following command to remove the `MultiClusterEngine` custom resource:
+
----
oc delete MultiClusterEngine --all
----
+
You can view the progress by entering the following command: 
+
----
oc get mch -o yaml
----

. Remove any potential remaining artifacts by running the clean-up script. 
+
*Note*: If `cert-manager` was manually installed in your cluster, be sure to review the commands in the clean-up script and remove commands that are specific to `cert-manager`.

.. Install the Helm CLI binary version 3.2.0, or later, by following the instructions at https://helm.sh/docs/intro/install/[Installing Helm].

.. Copy the following script into a file:
+
----
#!/bin/bash
MCE_NAMESPACE=<namespace>
oc delete mce --all -n $MCE_NAMESPACE
helm ls --namespace $MCE_NAMESPACE | cut -f 1 | tail -n +2 | xargs -n 1 helm delete --namespace $MCE_NAMESPACE
oc delete apiservice v1beta2.webhook.certmanager.k8s.io v1.admission.cluster.open-cluster-management.io v1.admission.work.open-cluster-management.io
oc delete clusterimageset --all
oc delete configmap -n $MCE_NAMESPACE cert-manager-controller cert-manager-cainjector-leader-election cert-manager-cainjector-leader-election-core
oc delete consolelink acm-console-link
oc delete crd klusterletaddonconfigs.agent.open-cluster-management.io placementbindings.policy.open-cluster-management.io policies.policy.open-cluster-management.io userpreferences.console.open-cluster-management.io searchservices.search.acm.com 
oc delete mutatingwebhookconfiguration cert-manager-webhook cert-manager-webhook-v1alpha1 ocm-mutating-webhook managedclustermutators.admission.cluster.open-cluster-management.io 
oc delete oauthclient multicloudingress
oc delete rolebinding -n kube-system cert-manager-webhook-webhook-authentication-reader
oc delete scc kui-proxy-scc
oc delete validatingwebhookconfiguration cert-manager-webhook cert-manager-webhook-v1alpha1 channels.apps.open.cluster.management.webhook.validator application-webhook-validator multiclusterengine-operator-validating-webhook ocm-validating-webhook
----
+
Replace `<namespace>` in the script with the name of the namespace where {product-title-short} was installed. Ensure that you specify the correct namespace, as the namespace is cleaned out and deleted. 

.. Run the script to remove any possible artifacts that remain from the previous installation. If there are no remaining artifacts, a message is returned that no resources were found.
+
*Note:* If you plan to reinstall the same {product-title-short} version, you can skip the next steps in this procedure and reinstall the custom resource. Proceed for a complete operator uninstall.

. Enter the following command to remove all of the related components and subscriptions:
+
----
oc delete subs --all
----

. Enter the following command to delete the `ClusterServiceVersion`:
+
----
oc delete clusterserviceversion --all
----

[#deleting-the-components-by-using-the-console]
== Deleting the components by using the console

When you use the {ocp} console to uninstall, you remove the operator. Complete the following steps to uninstall by using the console:

. In the {ocp-short} console navigation, select *Operators* > *Installed Operators* > *multicluster engine for Kubernetes*.

. Remove the `MultiClusterEngine` custom resource.
.. Select the tab for _Multiclusterengine_.

.. Select the _Options_ menu for the MultiClusterEngine custom resource.

.. Select *Delete MultiClusterEngine*.

. Run the clean-up script according to the procedure in xref:../install/uninstall.adoc#removing-a-multiclusterengine-instance-by-using-commands[Removing a MultiClusterEngine instance by using commands].
+
*Tip:* If you plan to reinstall the same {product-title-short} version, you can skip the rest of the steps in this procedure and reinstall the custom resource.

. Navigate to *Installed Operators*.

. Remove the _{product-title-short}_ operator by selecting the _Options_ menu and selecting *Uninstall operator*.
