[#troubleshooting-reinstallation-failure]
= Troubleshooting reinstallation failure

When reinstalling {product-title}, the pods do not start.

[#symptom-reinstallation-failure]
== Symptom: Reinstallation failure

If your pods do not start after you install {product-title-short}, it is likely that {product-title-short} was previously installed, and not all of the pieces were removed before you attempted this installation. 

In this case, the pods do not start after completing the installation process. 

[#resolving-the-problem-reinstallation-failure]
== Resolving the problem: Reinstallation failure

If you have this problem, complete the following steps: 

. Run the uninstallation process to remove the current components by following the steps in link:../install/uninstall.adoc#uninstalling[Uninstalling].

. Install the Helm CLI binary version 3.2.0, or later, by following the instructions at https://helm.sh/docs/intro/install/[Installing Helm].

. Ensure that your {ocp} CLI is configured to run `oc` commands. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.8/html/cli_tools/openshift-cli-oc#cli-getting-started[Getting started with the OpenShift CLI] in the {ocp-short} documentation for more information about how to configure the `oc` commands. 

. Copy the following script into a file:
+
----
#!/bin/bash
oc delete apiservice v1.admission.cluster.open-cluster-management.io v1.admission.work.open-cluster-management.io
oc delete validatingwebhookconfiguration multiclusterengines.multicluster.openshift.io
oc delete mce --all 
----
+
Replace `<namespace>` in the script with the name of the namespace where {product-title-short} was installed. Ensure that you specify the correct namespace, as the namespace is cleaned out and deleted. 

. Run the script to remove the artifacts from the previous installation. 

. Run the installation. See link:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online].


